sudo: false
language: node_js
cache: npm
node_js: node

env:
  global:
  - secure: "D/A4HBl/NupSJMKybKDFb6GerhaWZ/dDxtm1h/ZYF98eVdZs2cY6hEiykZn/P82uCn/BbPzt2vN6yGN2Sq1YzIdSNR8Nq7yImOgsrIWtU6KrR7o+8VZkG1IF6suhhB12rrRFRgWxbEashB3gqzkOGDf7/1+At2w4UfGfJMnmws/sMaxyjC2XHlCBmoTHBzTED2/VWGpBwQZ93bYsMiIATykdNj/+SKtcbcHqEuHN3/yeY+P2gsKDA27uNI8aFIoz3AKwARhDJlmEGwsyojqZpng3MHW9a2edVKzjPoyNAJu9sgHsLnJOr7WvcoK3BUoGHS0KpJwEZ03maVF3uPIpvdYepOem/pMLjQ0G3kU3T5ek+OcLFsAICB1pLcGH+gdBbzWnXNZAgcPHhcvZedTTLwiRfYrvPAkwfQqUzGsSCeXDLi10PB+V8XpdT2W4Y48ICkw5bY7le/IVNoQwYu2PC6fKM8pEkdYRiXg2kiZiPDbQ4rEYh4VuaRd+Snt2wDc3VT9w6liNh9OuujS+rATIL1YqxQVYFOf6wH5lFm/EPRPhKE1UKbAUI4LRO5PnDQT5PaLmU38Mq7NUJK5wqq5kMVNkU2GwpKvNhs/5wV+93cT1osL0CWRZpeoxGzkl59iPesPKWfC2MT/5XThqUaYCrTUA+sLi/WKGvWN15oz1BqE="

script:
- npm run build

before_deploy:
- openssl aes-256-cbc -K $encrypted_443220ed44d8_key -iv $encrypted_443220ed44d8_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
- chmod 0600 .travis/deploy_key
- echo 'snowowl.mastermovies.uk ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINaMerdSsl6DBKYMRwfSrIbNhbl6LYrF9/NaW3rI6Cqg' >> $HOME/.ssh/known_hosts

deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script: bash .travis/ci-deploy.sh

